spring.application.name=monitor-saude-api

spring.jackson.deserialization.fail-on-unknown-properties=true

server.port=8080

discord.webhook.url= (coloque a URL do seu Webhook aqui!)

monitor.delay=60000
